### get all produtos
GET {{baseUrl}}/products?page=0&linesPerPage=5&direction=ASC&orderBy=name

### Product by id
GET {{baseUrl}}/products/2
Content-Type: application/json

### Delet Product
DELETE {{baseUrl}}/products/7
Content-Type: application/json

### new Products
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name" : "New Product"
}

### Update Product
PUT {{baseUrl}}/products/6
Content-Type: application/json

{
    "name" : "Products Update"
}