-- Inserções para a tabela tb_category (apenas name e createdAt)
INSERT INTO tb_category (name, created_At)
VALUES ('Eletrônicos', NOW()),
       ('Livros', NOW()),
       ('Roupas Masculinas', NOW()),
       ('Roupas Femininas', NOW()),
       ('Calçados', NOW()),
       ('Casa e Decoração', NOW()),
       ('Beleza e Cuidados Pessoais', NOW()),
       ('Esportes', NOW()),
       ('Brinquedos', NOW()),
       ('Automotivo', NOW()),
       ('Saúde', NOW()),
       ('Alimentos e Bebidas', NOW()),
       ('Informática', NOW()),
       ('Telefones e Acessórios', NOW()),
       ('Games', NOW()),
       ('Filmes e Música', NOW()),
       ('Instrumentos Musicais', NOW()),
       ('Pet Shop', NOW()),
       ('Papelaria', NOW()),
       ('Ferramentas', NOW()),
       ('Moda Infantil', NOW()),
       ('Joias e Relógios', NOW()),
       ('Malas e Mochilas', NOW()),
       ('Cama, Mesa e Banho', NOW()),
       ('Eletrodomésticos', NOW()),
       ('Móveis', NOW()),
       ('Jardim e Piscina', NOW()),
       ('Artes e Artesanato', NOW()),
       ('Bebês', NOW()),
       ('Supermercado', NOW()),
       ('Construção', NOW()),
       ('Livros Técnicos', NOW()),
       ('Eletrônicos - Áudio', NOW()),
       ('Eletrônicos - Vídeo', NOW()),
       ('Material Elétrico', NOW()),
       ('Suplementos Alimentares', NOW()),
       ('Produtos Importados', NOW()),
       ('Produtos Orgânicos', NOW()),
       ('Vestuário Esportivo', NOW()),
       ('Equipamentos para Academia', NOW()),
       ('Pesca e Camping', NOW()),
       ('Natação', NOW()),
       ('Ciclismo', NOW()),
       ('Futebol', NOW()),
       ('Vôlei', NOW()),
       ('Basquete', NOW()),
       ('Tênis', NOW()),
       ('Golfe', NOW()),
       ('Skate', NOW()),
       ('Snowboard', NOW());